name: Check

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.17"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check Format
        run: |
          gofmt -s .
          go vet ./...
